### ISSUE TITLE
ForzaDSX is not connecting with DSX(Steam) or DualsenseX(github) via DSU

### ISSUE THREAD

**Issue by sunnyye1** [cosmii02/ForzaDSXlegacy#2]
Problem Description
With ForzaDSX detecting both Fora horizon 4 and DSX(Steam), adn the game correctly set to data out on, ip 127.0.0.1, port 5300 and dsx udp set to 6969. With other telementary app, the data ouput works, and other mod works with dsx over udp. However with ForzaDSX the UDP indicatio in DSX shows red(not connected)

Debug Ouput
Verbose Mode Enabled!
No Running Instances of Forza found. Waiting...
No Running Instances of Forza found. Waiting...
No Running Instances of Forza found. Waiting...
Forza and DSX are running. Let's Go!
DSX is using port 6969. Attempting to connect..
The Program is running. Please set the Forza data out to 127.0.0.1, port and verify the DualSenseX UDP Port is set to 6969

System Details
1. Windows 10 Pro 21H1
2. Forza Horizon 4 Ultimate edition
3. 2.1.0
4. Microsoft store PC

Steps to reproduce
It just wont work

Disabling firewall didnt work and other tools using the same port works

**Comment by cosmii02** [comment]
Out of curiosity, do you happen to own forza 5 as well. If yes, does the issue occur there for you as well?

**Comment by cosmii02** [comment]
Tested everything myself on 2 computers and everything worked perfectly, other users also reported it working.
This issue is something wrong with Windows installation.

**Comment by Maikenene** [comment]
After I started Forza DSX.exe, after launching Forza4, Forza DSX flashed back. Excuse me, what's the reason for this?
